services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: cekhoaks-app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:1.27
    container_name: cekhoaks-nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:16
    container_name: cekhoaks-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: cekhoaks-redis
    restart: unless-stopped

volumes:
  postgres_data: